version: '3'
services:
  nginx:
    image: 'nginx:latest'
    container_name: nginx
    restart: always
    ports:
      - '9003:80'
    volumes:
      - '~/data/nginx_home/nginx.conf:/etc/nginx/nginx.conf'