version: '3'
services:
  nginx:
    image: 'nginx:latest'
    container_name: web
    restart: always
    ports:
      - '9003:80'
    volumes:
      - "./config/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./config/etc/nginx/conf.d/:/etc/nginx/conf.d/"
      - "./web/:/usr/share/nginx/html/"
