version: '3'
services:
  mongo:
    image: 'mongo:latest'
    container_name: mongo
    restart: always
    user: root
    ports:
      - '9002:27017'
    volumes:
      - '~/data/mongo_home:/data/db'